esphome:
  name: bridge-lora-sx1262
  libraries:
    - "jgromes/RadioLib@^6.6.0"
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  version: 3

# import the components
external_components:
  - source:
      type: local
      path: ./ESPHomeLoRa/esphome/components
    components: [lora_mqtt, lora_mqtt_bridge]

spi:
  clk_pin: GPIO07
  mosi_pin: GPIO09
  miso_pin: GPIO08

# Defaults for xiao ESP32-S3 with B2B connector to WIO-SX1262
lora_mqtt_bridge:
  chip_type: SX1262
  cs_pin: GPIO41            # chip-select (or NSS) pin for LoRa radio
  reset_pin: GPIO42         # reset pin for LoRa radio
  dio_pin: GPIO39           # DIO0 pin for SX1276 or IRQ pin for SX1262
  dio1_pin: GPIO40          # DIO1 pin ONLY for SX1262a (BUSY)
  frequency: 868000000      # frequency to use
  # the options below are very dependent on your particular board and chip
  # not all combinations work
  # sync: 0xF3              # sets the sync word, defaults to 0x12
  # coding: 5               # sets the coding rate, defaults to 5
  # bandwidth: 250000       # sets the bandwidth, defaults to 125,000
  # spread: 12              # sets the spread, defaults to 7

mqtt:
  id: mqtt_broker
  broker: mosquitto.example.net
  username: homeassistant
  password: SuperSecret

# Depending on the board select either Ethernet or WiFi
#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk: GPIO0_IN
#  phy_addr: 1
#  power_pin: GPIO16

wifi:
  ssid: mywifi
  password: SuperSecret
